CREATE DATABASE SCHOOLDATABASE;

USE SCHOOLDATABASE;

CREATE TABLE SCHOOL(
    SchoolName VARCHAR(50) NOT NULL,
    PRIMARY KEY (SchoolName),
    Address VARCHAR(100)
);

CREATE TABLE CLASS(
    ClassID CHAR(5) NOT NULL,
    PRIMARY KEY(ClassID),
    ClassName VARCHAR(20)
);

CREATE TABLE PARENT(
    ID CHAR(10) NOT NULL,
    PRIMARY KEY(ID),
    FirstName VARCHAR(25),
    MidlleName VARCHAR(25),
	LastName VARCHAR(25),
    Relationship VARCHAR(20),
    Address VARCHAR(100)
);

CREATE TABLE STUDENT (
    FirstName VARCHAR(25),
    MiddleName VARCHAR(25),
    LastName VARCHAR(25),
    StudentID CHAR(6) NOT NULL,
    PRIMARY KEY(StudentID),
    BirthDay DATE,
    Address VARCHAR(100),
    Sex VARCHAR(10),
    SchoolName VARCHAR(50),
    ParentID CHAR(10),
    ClassID CHAR(5),
    FOREIGN KEY (ParentID) REFERENCES PARENT(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SchoolName) REFERENCES SCHOOL(SchoolName) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE Student_Email(
    StID CHAR(6) NOT NULL,
    StEmail VARCHAR(100) NOT NULL,
    PRIMARY KEY(StID,StEmail),
    FOREIGN KEY (StId) REFERENCES STUDENT(StudentID) ON DELETE CASCADE ON UPDATE CASCADE
   
);


CREATE TABLE Student_Telephone(
    StID CHAR(6) NOT NULL,
    StTelephone VARCHAR(10) NOT NULL,
    PRIMARY KEY(StID,StTelephone),
    FOREIGN KEY (StId) REFERENCES STUDENT(StudentID) ON DELETE CASCADE ON UPDATE CASCADE
   
);

CREATE TABLE Parent_Telephone(
    PId CHAR(10) NOT NULL,
    Telephone VARCHAR(10) NOT NULL,
    PRIMARY KEY(PId,Telephone),
    FOREIGN KEY (PId) REFERENCES PARENT(ID) ON DELETE CASCADE ON UPDATE CASCADE
   
);


CREATE TABLE EMPLOYEE(
    EmployeeId char(10) NOT NULL,
    PRIMARY KEY(EmployeeId),
    FirstName VARCHAR(25),
    MidlleName VARCHAR(25),
	LastName VARCHAR(25),
    Address VARCHAR(100),
    BirthDay date,
    Sex VARCHAR(10),
    ScName VARCHAR(50),
    FOREIGN KEY (ScName) REFERENCES SCHOOL(SchoolName) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE Employee_Email(
    EId CHAR(10) NOT NULL,
    EEmail VARCHAR(100) NOT NULL,
    PRIMARY KEY(EId,EEmail),
    FOREIGN KEY (EId) REFERENCES EMPLOYEE(EmployeeId) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE Employee_TelePhone(
    EId CHAR(10) NOT NULL,
    ETelePhone int(10) NOT NULL,
    PRIMARY KEY(EId,ETelePhone),
    FOREIGN KEY (EId) REFERENCES EMPLOYEE(EmployeeId) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE ADMIN(
    EId CHAR(10) NOT NULL,
    PRIMARY KEY (EId),
    ScName VARCHAR(50),
    FOREIGN KEY (EId) REFERENCES EMPLOYEE(EmployeeId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ScName) REFERENCES SCHOOL(SchoolName) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE TEACHER(
    EId CHAR(10) NOT NULL,
    TId CHAR(10) NOT NULL,
    PRIMARY KEY (EId,TId),
    FOREIGN KEY (EId) REFERENCES EMPLOYEE(EmployeeId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TEACHES_FOR(
    TeacherId CHAR(10) NOT NULL,
    ClassID  CHAR(5) NOT NULL, 
    PRIMARY KEY (TeacherId,ClassID),
    FOREIGN KEY (TeacherId) REFERENCES TEACHER(EId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NON_ACADEMIC(
    EId CHAR(10) NOT NULL,
    JobPost VARCHAR(100),
    FOREIGN KEY (EId) REFERENCES EMPLOYEE(EmployeeId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SUBJECT(
    SubID char(5) NOT NULL,
    PRIMARY KEY(SubID),
    Name VARCHAR(25),
    SchoolName VARCHAR(50),
    FOREIGN KEY (SchoolName) REFERENCES SCHOOL(SchoolName) ON DELETE CASCADE ON UPDATE CASCADE
);

	


CREATE TABLE TIME_TABLE(
    TableID char(6) NOT NULL,
    PRIMARY KEY(TableID),
    ClassID char(5),
    Discription VARCHAR(100),
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID) ON DELETE CASCADE ON UPDATE CASCADE
    
);



CREATE TABLE STUDIES(
    StID CHAR(6) NOT NULL,
    SubID char(5) NOT NULL,
    PRIMARY key(StID,SubID),
    FOREIGN KEY (StID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SubID) REFERENCES SUBJECT(SubID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EXAM(
    ExamID CHAR(6) NOT NULL,
    PRIMARY KEY(ExamID),
    Date date,
    SubID char(5),
    FOREIGN KEY (SubID) REFERENCES SUBJECT(SubID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE TAKE_EXAM(
    StID CHAR(6) NOT NULL,
    ExamID CHAR(6) NOT NULL,
    PRIMARY key(StID,ExamID),
    FOREIGN KEY (ExamID) REFERENCES EXAM(ExamID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (StID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE ON UPDATE CASCADE

);
